const APPLICATION_STATUSES = [
  'DRAFT',
  'AWAITING_PAYMENT',
  'PAID',
  'SUBMITTED',
  'UNDER_REVIEW',
  'ADDITIONAL_INFO_REQUIRED',
  'PROCESSING',
  'APPROVED',
  'COMPLETED',
  'DECLINED',
  'CANCELLED',
];

// Statuses an admin may move an application into.
const ADMIN_SETTABLE_STATUSES = [
  'SUBMITTED',
  'UNDER_REVIEW',
  'ADDITIONAL_INFO_REQUIRED',
  'PROCESSING',
  'APPROVED',
  'COMPLETED',
  'DECLINED',
  'CANCELLED',
];

// Statuses in which the client may still edit their draft.
const EDITABLE_STATUSES = ['DRAFT', 'AWAITING_PAYMENT'];

const PAYMENT_STATUSES = ['PENDING', 'PAID', 'FAILED', 'CANCELLED', 'EXPIRED'];

const DOCUMENT_TYPES = ['APPLICANT_PASSPORT_PHOTO', 'MANIFEST_CARD', 'SPONSOR_PASSPORT_PHOTO'];

const SPONSOR_RELATIONSHIPS = ['Parent', 'Brother/Sister', 'Spouse', 'Relative', 'Friend', 'Other'];

const FAMILY_RELATIONSHIPS = ['Spouse', 'Child', 'Parent', 'Brother/Sister', 'Relative', 'Other'];

const ADMIN_ROLES = ['SUPER_ADMIN', 'APPLICATION_OFFICER', 'FINANCE_OFFICER', 'VIEWER'];

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  APPLICATION_OFFICER: 'APPLICATION_OFFICER',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  VIEWER: 'VIEWER',
};

const MAX_FAMILY_MEMBERS = 20;

module.exports = {
  APPLICATION_STATUSES,
  ADMIN_SETTABLE_STATUSES,
  EDITABLE_STATUSES,
  PAYMENT_STATUSES,
  DOCUMENT_TYPES,
  SPONSOR_RELATIONSHIPS,
  FAMILY_RELATIONSHIPS,
  ADMIN_ROLES,
  ROLES,
  MAX_FAMILY_MEMBERS,
};
